### ISSUE TITLE
Support for aarch64-apple-darwin

### ISSUE THREAD

**Issue by cgilmore** [tuist/lightning_css#28]
- Elixir `1.17.2`
- Phoenix `1.7.14`
- lightning_css `0.5.0`
- Apple M1 Pro, Ventura `13.7`

First time trying out the library. When attempting to run the application, I'm getting the following error:

```
** (Mix) Could not start application lightning_css: exited in: LightningCSS.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) lightning_css is not available for architecture: aarch64-apple-darwin22.6.0
            (lightning_css 0.5.0) lib/lightning_css/architectures.ex:90: LightningCSS.Architectures.unsupported_arch/0
            (lightning_css 0.5.0) lib/lightning_css/paths.ex:12: LightningCSS.Paths.bin/0
            (lightning_css 0.5.0) lib/lightning_css/versions.ex:17: LightningCSS.Versions.bin/0
            (lightning_css 0.5.0) lib/lightning_css.ex:18: LightningCSS.start/2
            (kernel 9.2.4) application_master.erl:293: :application_master.start_it_old/4
```

I wasn't sure if this should be raised here or in the LightningCSS repo. I thought of mentioning it here first because I can see in [LightningCSS's GitHub workflow](https://github.com/parcel-bundler/lightningcss/blob/84ebbed7c4645da50ce9dee14001779531366cd6/.github/workflows/release.yml#L77) where they target a build for `aarch64-apple-darwin`.

One thing I notice is that what comes back from `:erlang.system_info(:system_architecture)` is `"aarch64-apple-darwin22.6.0"`. However, from NodeJS [`.arch()`](https://nodejs.org/api/os.html#osarch), [`.platform()`](https://nodejs.org/api/os.html#osplatform) and [`.release()`](https://nodejs.org/api/os.html#osrelease) comes back with `"arm64 darwin 22.6.0"`, which lines up closer to what this repo references with regards to [available targets](https://github.com/tuist/lightning_css/blob/391647b74d2a21b5dba5425f434f8a15e9833a2c/lib/lightning_css/architectures.ex#L12) that LightningCSS supports. So, this might be causing a discrepancy in discerning whether the library is available or not.

**Comment by joelpaulkoch** [comment]
I ran into the same issue. #29 provides a fix.
